import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      screens: {
        'xs': '480px',
      },
      fontFamily: {
        sans: ['"Nunito Sans"', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        heading: ['"Fraunces"', 'ui-serif', 'Georgia', 'Cambria', 'serif'],
        script: ['"Dancing Script"', 'cursive'],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        primary: {
          DEFAULT: "#C24E6B",
          foreground: "#FFFFFF",
          50: "#FBF1F4",
          100: "#F6E1E8",
          200: "#ECC2CF",
          300: "#DF9DB1",
          400: "#D17791",
          500: "#C24E6B",
          600: "#A93C58",
          700: "#8C2F47",
          800: "#70283A",
          900: "#5C2330",
          dark: "#8C2F47",
        },
        secondary: {
          DEFAULT: "#84934F",
          foreground: "#FFFFFF",
          50: "#F5F7EF",
          100: "#E9EEDB",
          200: "#D4DEB9",
          300: "#BBC990",
          400: "#A0B06B",
          500: "#84934F",
          600: "#69763D",
          700: "#515B30",
          800: "#404829",
          900: "#363C23",
        },
        honey: {
          DEFAULT: "#DE9F2E",
          50: "#FDF7E9",
          100: "#FAEAC4",
          200: "#F4D488",
          300: "#ECBC50",
          400: "#E2A52F",
          500: "#DE9F2E",
          600: "#BC8222",
          700: "#94661C",
        },
        plum: {
          DEFAULT: "#7C5FA8",
          50: "#F5F0FB",
          100: "#E8DDEF",
          200: "#D2BCE0",
          300: "#B89ACF",
          400: "#9C7BBD",
          500: "#7C5FA8",
          600: "#634D8A",
          700: "#4E3C6D",
        },
        gray: {
          50: "#FAF8F4",
          100: "#F2EEE7",
          200: "#E6DFD3",
          300: "#D4C9B8",
          400: "#B3A491",
          500: "#8E7E6A",
          600: "#6E6052",
          700: "#524739",
          800: "#392F26",
          900: "#241E18",
        },
      },
      backgroundImage: {
        'linen': "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='200'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3CfeColorMatrix type='saturate' values='0'/%3E%3C/filter%3E%3Crect width='200' height='200' filter='url(%23n)' opacity='0.045'/%3E%3C/svg%3E\")",
        'parchment': "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='400'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='turbulence' baseFrequency='0.35' numOctaves='3' stitchTiles='stitch'/%3E%3CfeColorMatrix type='saturate' values='0.3'/%3E%3C/filter%3E%3Crect width='400' height='400' filter='url(%23n)' opacity='0.028'/%3E%3C/svg%3E\")",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "stitch-draw": {
          from: { "stroke-dashoffset": "var(--stitch-length, 200)" },
          to: { "stroke-dashoffset": "0" },
        },
        "yarn-float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-4px)" },
        },
        "bar-fill": {
          from: { width: "0%" },
          to: { width: "var(--bar-width)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "stitch-draw": "stitch-draw 1.1s ease-in-out forwards",
        "yarn-float": "yarn-float 3.2s ease-in-out infinite",
        "bar-fill": "bar-fill 0.8s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
