uploads = []

[[generated]]
id = "Xdorx1jv4RrrdPqmpq2Nk"
uri = "file://attached_assets/char-aloo.png"
type = "image"
title = "generated_image"

[[generated]]
id = "SsIMKgquyUS7exj9Z_bRB"
uri = "file://attached_assets/char-yala.png"
type = "image"
title = "generated_image"

[[generated]]
id = "EKV9dzK2KsZ8wOZ5Sbl7j"
uri = "file://attached_assets/char-bee.png"
type = "image"
title = "generated_image"

[[generated]]
id = "J0CDEse6HY2erGPcdlYdq"
uri = "file://attached_assets/char-sheep.png"
type = "image"
title = "generated_image"

[[generated]]
id = "cfVjAVj0HccI-bjFVW-Bf"
uri = "file://attached_assets/char-ashi.png"
type = "image"
title = "generated_image"

[[generated]]
id = "IyoC0qIcIyScOiIZnVdsE"
uri = "file://public/characters/char-aloo.png"
type = "image"
title = "aloo shitzu amigurumi"

[[generated]]
id = "ywbBC4OxTvAPsp21YKYsK"
uri = "file://public/characters/char-ashi.png"
type = "image"
title = "ashi maltipoo amigurumi"

[[generated]]
id = "HlPaPuT3L_tO0gpibFaAF"
uri = "file://public/characters/char-yala.png"
type = "image"
title = "yala desi elephant amigurumi"

[[outputs]]
id = "P2idT6M6wrM4S9n0Us7WR"
uri = "file://public/characters/char-aloo-transparent.png"
type = "image"
title = "Aloo — NEW Shih Tzu"

[[outputs]]
id = "UD1g82zA9DHqlDc3s1e4j"
uri = "file://public/characters/char-ashi-transparent.png"
type = "image"
title = "Ashi — NEW Maltipoo"

[[outputs]]
id = "T_6c_-5myT0QHxzbnNdhB"
uri = "file://public/characters/char-yala-transparent.png"
type = "image"
title = "Yala — NEW Desi Elephant"
