import React, { useState, useEffect } from 'react';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';
import { useMutation } from '@tanstack/react-query';
import { Sparkles } from 'lucide-react';
import { PatternInputFormData, Pattern } from '@/lib/types';
import PatternGenLoader from './PatternGenLoader';
import ProjectTypeCards from './ProjectTypeCards';
import SizeSlider from './SizeSlider';
import DifficultySelector from './DifficultySelector';
import MaterialsList from './MaterialsList';
import PreviewPanel from './PreviewPanel';

interface PatternInputProps {
  onPatternCreated: (pattern: Pattern) => void;
}

const PatternInputRefactored: React.FC<PatternInputProps> = ({ onPatternCreated }) => {
  const { toast } = useToast();
  const [formData, setFormData] = useState<PatternInputFormData>({
    prompt: '',
    projectType: '',
    skillLevel: '',
    yarnType: '',
    size: '10 cm',
  });
  const [file, setFile] = useState<File | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationStage, setGenerationStage] = useState<'prompt' | 'pattern' | 'images' | 'complete'>('prompt');
  
  // Materials will be generated by AI and displayed in the pattern viewer, not as inputs

  // Handle prompt input change
  const handlePromptChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setFormData(prev => ({ ...prev, prompt: e.target.value }));
  };

  // Handle project type selection
  const handleProjectTypeSelect = (type: string, customValue?: string) => {
    if (type === 'custom' && customValue) {
      setFormData(prev => ({ ...prev, projectType: customValue }));
    } else {
      setFormData(prev => ({ ...prev, projectType: type }));
    }
  };

  // Handle size change
  const handleSizeChange = (size: string) => {
    setFormData(prev => ({ ...prev, size }));
  };

  // Handle difficulty selection
  const handleDifficultySelect = (level: string) => {
    setFormData(prev => ({ ...prev, skillLevel: level }));
  };

  // Handle file upload
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
    }
  };

  // Materials will be handled in the pattern viewer after generation

  // Generate pattern mutation
  const generatePatternMutation = useMutation({
    mutationFn: async (data: PatternInputFormData) => {
      const res = await apiRequest('POST', '/api/generate-pattern', {
        prompt: data.prompt,
        projectType: data.projectType,
        skillLevel: data.skillLevel,
        yarnType: data.yarnType || undefined,
        size: data.size || undefined
      });
      return res.json();
    }
  });

  // Generate image mutation
  const generateImageMutation = useMutation({
    mutationFn: async (data: { prompt: string, projectType: string, yarnType?: string }) => {
      const res = await apiRequest('POST', '/api/generate-image', {
        prompt: data.prompt,
        type: 'final',
        projectType: data.projectType,
        yarnType: data.yarnType
      });
      return res.json();
    }
  });

  // Save pattern mutation
  const savePatternMutation = useMutation({
    mutationFn: async (pattern: Omit<Pattern, 'id' | 'createdAt'>) => {
      const res = await apiRequest('POST', '/api/patterns', pattern);
      return res.json();
    }
  });

  // Handle pattern generation
  const handleGeneratePattern = async () => {
    if (!formData.prompt || !formData.projectType || !formData.skillLevel) {
      toast({
        title: "Missing information",
        description: "Please fill in the prompt, project type, and skill level.",
        variant: "destructive"
      });
      return;
    }

    setIsGenerating(true);
    setGenerationStage('prompt');

    try {
      // Generate the pattern
      setGenerationStage('pattern');
      const generatedPatternData = await generatePatternMutation.mutateAsync(formData);
      
      // Generate an image for the pattern
      setGenerationStage('images');
      const imagePrompt = `${generatedPatternData.title || formData.prompt}`;
      const imageResponse = await generateImageMutation.mutateAsync({
        prompt: imagePrompt,
        projectType: formData.projectType,
        yarnType: formData.yarnType
      });

      // Prepare pattern for saving
      const patternToSave = {
        title: generatedPatternData.title,
        projectType: formData.projectType,
        skillLevel: formData.skillLevel,
        yarnType: formData.yarnType || undefined,
        size: formData.size || undefined,
        endProductImage: imageResponse.url,
        materialsNotes: generatedPatternData.materialsNotes || "",
        yarnRequirements: generatedPatternData.yarnRequirements || [],
        sections: generatedPatternData.sections.map((section: any) => ({
          name: section.name,
          notes: section.notes || "",
          locked: false,
          partImageUrl: section.partImageUrl || null,
          steps: section.steps.map((step: any) => ({
            id: step.id,
            text: step.text,
            locked: false,
            count: 0,
            notes: '',
            photo: null,
            aiStepImage: null,
            completed: false
          }))
        }))
      };

      // Save the pattern
      const savedPattern = await savePatternMutation.mutateAsync(patternToSave);
      
      // Set the completion stage
      setGenerationStage('complete');
      
      // Give a short delay to show the completion animation
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      // Pass the saved pattern to the parent component
      onPatternCreated(savedPattern);
      
      toast({
        title: "Pattern Generated!",
        description: `Your "${savedPattern.title}" pattern is ready.`,
      });
    } catch (error) {
      console.error('Error generating pattern:', error);
      toast({
        title: "Generation Failed",
        description: "There was an error generating your pattern. Please try again.",
        variant: "destructive"
      });
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6">
      <div className="bg-white shadow-md rounded-2xl p-4 sm:p-6 mb-8">
        <h2 className="text-2xl font-bold text-secondary-600 font-heading mb-6">Create a New Pattern</h2>
        
        {/* Loading Animation */}
        {isGenerating && (
          <PatternGenLoader stage={generationStage} />
        )}
        
        {/* Main Content */}
        <div className={isGenerating ? 'opacity-50 pointer-events-none' : ''}>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Left Column - Input Fields */}
            <div className="lg:col-span-2 space-y-4 sm:space-y-6">
              {/* Prompt Input */}
              <div>
                <label htmlFor="prompt" className="block text-sm font-medium text-secondary-600 mb-2">
                  Describe Your Pattern
                </label>
                <div className="rounded-xl border border-gray-300 shadow-sm focus-within:ring-2 focus-within:ring-primary-300">
                  <textarea 
                    id="prompt" 
                    name="prompt"
                    rows={4} 
                    className="w-full p-4 rounded-xl outline-none resize-none"
                    placeholder="Describe what you want to crochet... e.g. 'a cute baby tiger plushie with striped pattern'"
                    value={formData.prompt}
                    onChange={handlePromptChange}
                  />
                </div>
              </div>
              
              {/* Project Type */}
              <div>
                <label className="block text-sm font-medium text-secondary-600 mb-2">
                  Project Type
                </label>
                <ProjectTypeCards 
                  selectedType={formData.projectType} 
                  onSelect={handleProjectTypeSelect} 
                />
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Difficulty Level */}
                <div>
                  <DifficultySelector 
                    selectedLevel={formData.skillLevel} 
                    onSelect={handleDifficultySelect} 
                  />
                </div>
                
                {/* Size Slider */}
                <div>
                  <SizeSlider 
                    value={formData.size || '10 cm'}
                    onChange={handleSizeChange}
                  />
                </div>
              </div>
              
              {/* Yarn Type */}
              <div>
                <label className="block text-sm font-medium text-secondary-600 mb-2">
                  Yarn Type (Optional)
                </label>
                <input 
                  type="text"
                  name="yarnType"
                  className="block w-full px-4 py-3 bg-white border border-gray-300 rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-primary-300 focus:border-primary-300"
                  placeholder="Leave blank for AI recommendations"
                  value={formData.yarnType}
                  onChange={(e) => setFormData(prev => ({ ...prev, yarnType: e.target.value }))}
                />
              </div>
              
              {/* Reference Image Upload */}
              <div>
                <label className="block text-sm font-medium text-secondary-600 mb-2">
                  Optional Reference Image
                </label>
                <div className="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-xl">
                  <div className="space-y-1 text-center">
                    <svg className="mx-auto h-12 w-12 text-secondary-400" stroke="currentColor" fill="none" viewBox="0 0 48 48">
                      <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                    <div className="flex text-sm text-gray-600">
                      <label htmlFor="file-upload" className="relative cursor-pointer bg-white rounded-md font-medium text-primary hover:text-primary-400 focus-within:outline-none">
                        <span>Upload an image</span>
                        <input
                          id="file-upload"
                          name="file-upload"
                          type="file"
                          className="sr-only"
                          accept="image/*"
                          onChange={handleFileChange}
                        />
                      </label>
                      <p className="pl-1">or drag and drop</p>
                    </div>
                    <p className="text-xs text-gray-500">
                      PNG, JPG, GIF up to 10MB
                    </p>
                    {file && (
                      <p className="text-sm text-primary-600">
                        Selected: {file.name}
                      </p>
                    )}
                  </div>
                </div>
              </div>
            </div>
            
            {/* Right Column - Preview Only */}
            <div className="space-y-6">
              {/* Pattern Preview */}
              <PreviewPanel 
                prompt={formData.prompt}
                projectType={formData.projectType}
                yarnType={formData.yarnType}
              />
            </div>
          </div>
          
          {/* Generate Pattern Button */}
          <div className="mt-8 flex justify-center">
            <button
              type="button"
              className={`inline-flex justify-center items-center px-8 py-3 border border-transparent rounded-full shadow-sm text-base font-medium text-white bg-primary hover:bg-primary-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary transition-all duration-200 ${
                isGenerating ? 'opacity-75 cursor-not-allowed' : ''
              }`}
              onClick={handleGeneratePattern}
              disabled={isGenerating}
            >
              <Sparkles className="h-5 w-5 mr-2" />
              {isGenerating ? 'Generating...' : 'Generate Pattern'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PatternInputRefactored;