import React, { useState, useEffect } from 'react';
import { useToast } from '@/hooks/use-toast';
import { ToastAction } from '@/components/ui/toast';
import { apiRequest } from '@/lib/queryClient';
import { useMutation } from '@tanstack/react-query';
import { Key, AlertCircle, ExternalLink } from 'lucide-react';
import { getOrdinalSuffix } from '@/lib/dateUtils';
import { Sparkles } from 'lucide-react';
import { PatternInputFormData, Pattern } from '../lib/types';
import PatternGenLoader from './PatternGenLoader';
import ThreadDivider from './ThreadDivider';
import ProjectTypeCards from './ProjectTypeCards';
import SizeSlider from './SizeSlider';
import DifficultySelector from './DifficultySelector';
import PreviewPanel from './PreviewPanel';

interface PatternInputProps {
  onPatternCreated: (pattern: Pattern) => void;
}

const PatternInputRefactored: React.FC<PatternInputProps> = ({ onPatternCreated }) => {
  const { toast } = useToast();
  const [formData, setFormData] = useState<PatternInputFormData>({
    prompt: '',
    projectType: '',
    skillLevel: '',
    yarnType: '',
    size: '10 cm',
  });
  const [file, setFile] = useState<File | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationStage, setGenerationStage] = useState<'prompt' | 'pattern' | 'images' | 'complete'>('prompt');
  
  // Materials will be generated by AI and displayed in the pattern viewer, not as inputs

  // Handle prompt input change
  const handlePromptChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setFormData((prev: PatternInputFormData) => ({ ...prev, prompt: e.target.value }));
  };

  // Handle project type selection
  const handleProjectTypeSelect = (type: string, customValue?: string) => {
    if (type === 'custom' && customValue) {
      setFormData((prev: PatternInputFormData) => ({ ...prev, projectType: customValue }));
    } else {
      setFormData((prev: PatternInputFormData) => ({ ...prev, projectType: type }));
    }
  };

  // Handle size change
  const handleSizeChange = (size: string) => {
    setFormData((prev: PatternInputFormData) => ({ ...prev, size }));
  };

  // Handle difficulty selection
  const handleDifficultySelect = (level: string) => {
    setFormData((prev: PatternInputFormData) => ({ ...prev, skillLevel: level }));
  };

  // Handle file upload
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const selectedFile = e.target.files[0];
      
      // Validate file type
      const validTypes = ['image/jpeg', 'image/png', 'image/gif'];
      if (!validTypes.includes(selectedFile.type)) {
        toast({
          title: "Invalid file type",
          description: "Please upload a JPG, PNG, or GIF image.",
          variant: "destructive"
        });
        return;
      }
      
      // Validate file size (10MB limit)
      if (selectedFile.size > 10 * 1024 * 1024) {
        toast({
          title: "File too large",
          description: "Please upload an image smaller than 10MB.",
          variant: "destructive"
        });
        return;
      }
      
      setFile(selectedFile);
      
      // Update the prompt with file description
      setFormData((prev: PatternInputFormData) => ({
        ...prev,
        prompt: prev.prompt 
          ? `${prev.prompt} (Reference image: ${selectedFile.name})`
          : `Create a crochet pattern based on the uploaded reference image (${selectedFile.name})`
      }));
      
      toast({
        title: "Reference Image Added",
        description: "Your image has been added as a reference for the pattern generation.",
      });
    }
  };

  // Materials will be handled in the pattern viewer after generation

  // Generate pattern mutation
  const generatePatternMutation = useMutation({
    mutationFn: async (data: PatternInputFormData) => {
      const res = await apiRequest('POST', '/api/generate-pattern', {
        prompt: data.prompt,
        projectType: data.projectType,
        skillLevel: data.skillLevel,
        yarnType: data.yarnType || undefined,
        size: data.size || undefined
      });
      return res.json();
    }
  });

  // Generate image mutation
  const generateImageMutation = useMutation({
    mutationFn: async (data: { prompt: string, projectType: string, yarnType?: string }) => {
      const res = await apiRequest('POST', '/api/generate-image', {
        prompt: data.prompt,
        type: 'final',
        projectType: data.projectType,
        yarnType: data.yarnType
      });
      return res.json();
    }
  });

  // Save pattern mutation
  const savePatternMutation = useMutation({
    mutationFn: async (pattern: Omit<Pattern, 'id' | 'createdAt'>) => {
      const res = await apiRequest('POST', '/api/patterns', pattern);
      return res.json();
    }
  });

  // Handle pattern generation
  const handleGeneratePattern = async () => {
    if (!formData.prompt || !formData.projectType || !formData.skillLevel) {
      toast({
        title: "Missing information",
        description: "Please fill in the prompt, project type, and skill level.",
        variant: "destructive"
      });
      return;
    }

    setIsGenerating(true);
    setGenerationStage('prompt');

    try {
      // Generate the pattern
      setGenerationStage('pattern');
      const generatedPatternData = await generatePatternMutation.mutateAsync(formData);
      
      // Generate an image for the pattern
      setGenerationStage('images');
      const imagePrompt = `${generatedPatternData.title || formData.prompt}`;
      const imageResponse = await generateImageMutation.mutateAsync({
        prompt: imagePrompt,
        projectType: formData.projectType,
        yarnType: formData.yarnType
      });

      // Prepare pattern for saving
      const patternToSave = {
        title: generatedPatternData.title,
        description: generatedPatternData.description || `A ${formData.skillLevel} level ${formData.projectType} crochet pattern.`,
        projectType: formData.projectType,
        skillLevel: formData.skillLevel,
        yarnType: formData.yarnType || undefined,
        size: formData.size || undefined,
        imgUrl: imageResponse.url, // Main image
        endProductImage: imageResponse.url, // Product image
        difficultyLevel: formData.skillLevel, // Map skill level to difficulty level
        completed: false, // New pattern starts as not completed
        materialsNotes: generatedPatternData.materialsNotes || "",
        yarnRequirements: generatedPatternData.yarnRequirements || [],
        hookRequirements: generatedPatternData.hookRequirements || [],
        notionsRequirements: generatedPatternData.notionsRequirements || [],
        toolRequirements: generatedPatternData.toolRequirements || [],
        sections: generatedPatternData.sections.map((section: any) => ({
          name: section.name,
          notes: section.notes || "",
          locked: false,
          partImageUrl: section.partImageUrl || null,
          steps: section.steps.map((step: any) => ({
            id: step.id,
            text: step.text,
            locked: false,
            count: 0,
            notes: '',
            photo: null,
            aiStepImage: null,
            completed: false
          }))
        }))
      };

      // Save the pattern
      const savedPattern = await savePatternMutation.mutateAsync(patternToSave);
      
      // Set the completion stage
      setGenerationStage('complete');
      
      // Give a short delay to show the completion animation
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      // Pass the saved pattern to the parent component
      onPatternCreated(savedPattern);
      
      toast({
        title: "Pattern Generated Successfully!",
        description: `Your "${savedPattern.title}" pattern is ready! You can now view the pattern details, instructions, and generate section images.`,
        duration: 6000,
      });
    } catch (error) {
      console.error('Error generating pattern:', error);
      
      // Provide more specific error messages based on error type
      let errorDescription = "There was an error generating your pattern. Please try again.";
      const errorString = String(error);
      
      // Check for API key related errors
      const isApiKeyError = errorString.includes('OPENAI_API_KEY') || 
                         errorString.includes('API key') || 
                         errorString.includes('authentication') || 
                         errorString.includes('Unauthorized') || 
                         errorString.includes('401') || 
                         errorString.includes('403') || 
                         errorString.includes('key invalid');
      
      if (isApiKeyError) {
        // Use the special API warning toast variant for API key issues
        toast({
          title: "OpenAI API Key Required",
          description: "To generate your crochet pattern, please add a valid OpenAI API key in your environment variables.",
          variant: "apiWarning",
          action: <ToastAction altText="Visit OpenAI" onClick={() => window.open('https://platform.openai.com/account/api-keys', '_blank')}>
                   <Key className="mr-1 h-4 w-4" />Get API Key
                </ToastAction>,
          duration: 10000, // Show for longer (10 seconds)
        });
      } 
      // Rate Limit Errors
      else if (errorString.includes('rate limit') || errorString.includes('429')) {
        toast({
          title: "Rate Limit Reached",
          description: "OpenAI API rate limit reached for pattern generation. Please try again in a few minutes when your quota resets.",
          variant: "apiWarning",
          duration: 8000,
        });
      } 
      // Timeout Errors
      else if (errorString.includes('timeout') || errorString.includes('timed out')) {
        toast({
          title: "Generation Timed Out",
          description: "The pattern generation request timed out. Try a simpler description or check your network connection.",
          variant: "apiWarning",
          duration: 8000,
        });
      }
      // Network Errors
      else if (errorString.includes('network') || errorString.includes('connection') || errorString.includes('ECONNRESET')) {
        toast({
          title: "Network Error",
          description: "Could not connect to the OpenAI API. Please check your internet connection and try again.",
          variant: "apiWarning",
          duration: 8000,
        });
      }
      // Billing Errors
      else if (errorString.includes('billing') || errorString.includes('payment') || errorString.includes('quota')) {
        toast({
          title: "OpenAI Billing Issue",
          description: "There's a billing issue with your OpenAI account. Please check your payment information or usage quota.",
          variant: "apiWarning",
          action: <ToastAction altText="Check Billing" onClick={() => window.open('https://platform.openai.com/account/billing', '_blank')}>
                    <ExternalLink className="mr-1 h-4 w-4" />Check Billing
                 </ToastAction>,
          duration: 10000,
        });
      }
      // Content Policy Violations
      else if (errorString.includes('content policy') || errorString.includes('safety') || errorString.includes('violation')) {
        toast({
          title: "Content Policy Violation",
          description: "Your pattern request may violate OpenAI's content policy. Please ensure your description doesn't contain inappropriate content.",
          variant: "apiWarning",
          action: <ToastAction altText="Learn More" onClick={() => window.open('https://openai.com/policies/usage-policies', '_blank')}>
                    <AlertCircle className="mr-1 h-4 w-4" />Learn More
                 </ToastAction>,
          duration: 10000,
        });
      } 
      // Generic Fallback Error
      else {
        toast({
          title: "Pattern Generation Failed",
          description: `Could not generate your crochet pattern. Error details: ${errorString.substring(0, 50)}${errorString.length > 50 ? '...' : ''}`,
          variant: "destructive",
          duration: 6000,
        });
      }
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="mx-auto max-w-5xl">
      <header className="mb-6 text-center sm:mb-8">
        <h1 className="font-heading text-3xl font-semibold tracking-tight text-foreground sm:text-4xl">
          Let&rsquo;s make something lovely
        </h1>
        <p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground sm:text-base">
          Describe what you&rsquo;d like to crochet and we&rsquo;ll spin up a full pattern&nbsp;&mdash; stitches, sections and materials.
        </p>
        <ThreadDivider animated className="mx-auto mt-4 max-w-[16rem]" />
      </header>

      <div className="surface-card mb-8 p-4 sm:p-7">
        {/* Loading Animation */}
        {isGenerating && (
          <PatternGenLoader stage={generationStage} />
        )}
        
        {/* Main Content */}
        <div className={isGenerating ? 'opacity-50 pointer-events-none' : ''}>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Left Column - Input Fields */}
            <div className="lg:col-span-2 space-y-4 sm:space-y-6">
              {/* Prompt Input */}
              <div>
                <label htmlFor="prompt" className="block text-sm font-medium text-secondary-600 mb-2">
                  Describe Your Pattern
                </label>
                <div className="rounded-xl border border-gray-300 shadow-sm focus-within:ring-2 focus-within:ring-primary-300">
                  <textarea 
                    id="prompt" 
                    name="prompt"
                    rows={4} 
                    className="w-full p-4 rounded-xl outline-none resize-none"
                    placeholder="Describe what you want to crochet... e.g. 'a cute baby tiger plushie with striped pattern'"
                    value={formData.prompt}
                    onChange={handlePromptChange}
                  />
                </div>
              </div>
              
              {/* Project Type */}
              <div>
                <label className="block text-sm font-medium text-secondary-600 mb-2">
                  Project Type
                </label>
                <ProjectTypeCards 
                  selectedType={formData.projectType} 
                  onSelect={handleProjectTypeSelect} 
                />
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Difficulty Level */}
                <div>
                  <DifficultySelector 
                    selectedLevel={formData.skillLevel} 
                    onSelect={handleDifficultySelect} 
                  />
                </div>
                
                {/* Size Slider */}
                <div>
                  <SizeSlider 
                    value={formData.size || '10 cm'}
                    onChange={handleSizeChange}
                  />
                </div>
              </div>
              
              {/* Yarn Type */}
              <div>
                <label className="block text-sm font-medium text-secondary-600 mb-2">
                  Yarn Type (Optional)
                </label>
                <input 
                  type="text"
                  name="yarnType"
                  className="block w-full px-4 py-3 bg-white border border-gray-300 rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-primary-300 focus:border-primary-300"
                  placeholder="Leave blank for AI recommendations"
                  value={formData.yarnType}
                  onChange={(e) => setFormData((prev: PatternInputFormData) => ({ ...prev, yarnType: e.target.value }))}
                />
              </div>
              
              {/* Reference Image Upload */}
              <div>
                <label className="block text-sm font-medium text-secondary-600 mb-2">
                  Optional Reference Image
                </label>
                <div className="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-xl">
                  <div className="space-y-1 text-center">
                    <svg className="mx-auto h-12 w-12 text-secondary-400" stroke="currentColor" fill="none" viewBox="0 0 48 48">
                      <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                    <div className="flex text-sm text-gray-600">
                      <label htmlFor="file-upload" className="relative cursor-pointer bg-white rounded-md font-medium text-primary hover:text-primary-400 focus-within:outline-none">
                        <span>Upload an image</span>
                        <input
                          id="file-upload"
                          name="file-upload"
                          type="file"
                          className="sr-only"
                          accept="image/*"
                          onChange={handleFileChange}
                        />
                      </label>
                      <p className="pl-1">or drag and drop</p>
                    </div>
                    <p className="text-xs text-gray-500">
                      PNG, JPG, GIF up to 10MB
                    </p>
                    {file && (
                      <p className="text-sm text-primary-600">
                        Selected: {file.name}
                      </p>
                    )}
                  </div>
                </div>
              </div>
            </div>
            
            {/* Right Column - Preview Only */}
            <div className="space-y-6">
              {/* Pattern Preview */}
              <PreviewPanel 
                prompt={formData.prompt}
                projectType={formData.projectType}
                yarnType={formData.yarnType}
              />
            </div>
          </div>
          
          {/* Generate Pattern Button */}
          <div className="mt-8 flex justify-center">
            <button
              type="button"
              className={`inline-flex items-center justify-center gap-2 rounded-full bg-primary px-8 py-3.5 text-base font-semibold text-primary-foreground shadow-sm transition-all duration-200 hover:bg-primary-600 hover:shadow-md focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 motion-safe:hover:-translate-y-0.5 ${
                isGenerating ? 'cursor-not-allowed opacity-75' : ''
              }`}
              onClick={handleGeneratePattern}
              disabled={isGenerating}
            >
              <Sparkles className="h-5 w-5" />
              {isGenerating ? 'Generating…' : 'Generate Pattern'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PatternInputRefactored;