import React, { useState } from 'react';
import { useToast } from '@/hooks/use-toast';
import { ToastAction } from '@/components/ui/toast';
import { apiRequest } from '@/lib/queryClient';
import { useMutation } from '@tanstack/react-query';
import { Sparkles } from 'lucide-react';
import { PatternInputFormData, Pattern } from '../lib/types';

interface PatternInputProps {
  onPatternCreated: (pattern: Pattern) => void;
}

const PatternInputRefactored: React.FC<PatternInputProps> = ({ onPatternCreated }) => {
  const { toast } = useToast();
  const [formData, setFormData] = useState<PatternInputFormData>({
    prompt: '',
    projectType: '',
    skillLevel: '',
    yarnType: '',
    size: '10 cm',
  });
  const [file, setFile] = useState<File | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationStage, setGenerationStage] = useState<'prompt' | 'pattern' | 'images' | 'complete'>('prompt');
  const [wizardStep, setWizardStep] = useState(0);
  const [wizardColors, setWizardColors] = useState<string[]>([]);

  const WIZARD_STEPS = ["Item", "Details", "Yarn & Colours", "Inspiration", "Review"];
  const CATEGORIES = [
    { id: "Amigurumi",  label: "Toys & Amigurumi", emoji: "🧸", color: "#C24E6B" },
    { id: "Wearable",   label: "Wearables",         emoji: "👒", color: "#7C5FA8" },
    { id: "Home Decor", label: "Home Decor",         emoji: "🏠", color: "#84934F" },
    { id: "Accessory",  label: "Accessories",        emoji: "👜", color: "#D4921A" },
    { id: "Other",      label: "Other",              emoji: "✨", color: "#3D8FA3" },
  ];
  const SKILL_LEVELS = [
    { id: "Beginner",     emoji: "🌱", desc: "First-timers welcome" },
    { id: "Intermediate", emoji: "🌿", desc: "Some experience needed" },
    { id: "Advanced",     emoji: "🌳", desc: "Complex techniques" },
  ];
  const YARN_TYPES = ["Cotton", "Wool", "Acrylic", "Blend", "Mohair", "Let AI decide"];
  const COLOR_PALETTE = [
    "#C24E6B","#7C5FA8","#84934F","#D4921A","#3D8FA3",
    "#F0C840","#E88050","#C8A0D8","#90C898","#F0A0B8",
    "#E8D0C0","#B0D0E8","#D8E0B0","#F8E8C0","#5C3A28",
  ];
  const SIZE_OPTIONS = ["5 cm", "10 cm", "15 cm", "20 cm", "30 cm", "40 cm+"];

  const canAdvance = () => {
    if (wizardStep === 0) return !!formData.projectType;
    if (wizardStep === 1) return !!formData.prompt && !!formData.skillLevel;
    return true;
  };

  // Materials will be generated by AI and displayed in the pattern viewer, not as inputs

  // Handle prompt input change
  const handlePromptChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setFormData((prev: PatternInputFormData) => ({ ...prev, prompt: e.target.value }));
  };

  // Handle project type selection
  const handleProjectTypeSelect = (type: string, customValue?: string) => {
    if (type === 'custom' && customValue) {
      setFormData((prev: PatternInputFormData) => ({ ...prev, projectType: customValue }));
    } else {
      setFormData((prev: PatternInputFormData) => ({ ...prev, projectType: type }));
    }
  };

  // Handle size change
  const handleSizeChange = (size: string) => {
    setFormData((prev: PatternInputFormData) => ({ ...prev, size }));
  };

  // Handle difficulty selection
  const handleDifficultySelect = (level: string) => {
    setFormData((prev: PatternInputFormData) => ({ ...prev, skillLevel: level }));
  };

  // Handle file upload
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const selectedFile = e.target.files[0];
      
      // Validate file type
      const validTypes = ['image/jpeg', 'image/png', 'image/gif'];
      if (!validTypes.includes(selectedFile.type)) {
        toast({
          title: "Invalid file type",
          description: "Please upload a JPG, PNG, or GIF image.",
          variant: "destructive"
        });
        return;
      }
      
      // Validate file size (10MB limit)
      if (selectedFile.size > 10 * 1024 * 1024) {
        toast({
          title: "File too large",
          description: "Please upload an image smaller than 10MB.",
          variant: "destructive"
        });
        return;
      }
      
      setFile(selectedFile);
      
      // Update the prompt with file description
      setFormData((prev: PatternInputFormData) => ({
        ...prev,
        prompt: prev.prompt 
          ? `${prev.prompt} (Reference image: ${selectedFile.name})`
          : `Create a crochet pattern based on the uploaded reference image (${selectedFile.name})`
      }));
      
      toast({
        title: "Reference Image Added",
        description: "Your image has been added as a reference for the pattern generation.",
      });
    }
  };

  // Materials will be handled in the pattern viewer after generation

  // Generate pattern mutation
  const generatePatternMutation = useMutation({
    mutationFn: async (data: PatternInputFormData) => {
      const res = await apiRequest('POST', '/api/generate-pattern', {
        prompt: data.prompt,
        projectType: data.projectType,
        skillLevel: data.skillLevel,
        yarnType: data.yarnType || undefined,
        size: data.size || undefined
      });
      return res.json();
    }
  });

  // Generate image mutation
  const generateImageMutation = useMutation({
    mutationFn: async (data: { prompt: string, projectType: string, yarnType?: string }) => {
      const res = await apiRequest('POST', '/api/generate-image', {
        prompt: data.prompt,
        type: 'final',
        projectType: data.projectType,
        yarnType: data.yarnType
      });
      return res.json();
    }
  });

  // Save pattern mutation
  const savePatternMutation = useMutation({
    mutationFn: async (pattern: Omit<Pattern, 'id' | 'createdAt'>) => {
      const res = await apiRequest('POST', '/api/patterns', pattern);
      return res.json();
    }
  });

  // Handle pattern generation
  const handleGeneratePattern = async () => {
    if (!formData.prompt || !formData.projectType || !formData.skillLevel) {
      toast({
        title: "Missing information",
        description: "Please fill in the prompt, project type, and skill level.",
        variant: "destructive"
      });
      return;
    }

    setIsGenerating(true);
    setGenerationStage('prompt');

    try {
      // Generate the pattern
      setGenerationStage('pattern');
      const generatedPatternData = await generatePatternMutation.mutateAsync(formData);
      
      // Generate an image for the pattern
      setGenerationStage('images');
      const imagePrompt = `${generatedPatternData.title || formData.prompt}`;
      const imageResponse = await generateImageMutation.mutateAsync({
        prompt: imagePrompt,
        projectType: formData.projectType,
        yarnType: formData.yarnType
      });

      // Prepare pattern for saving
      const patternToSave = {
        title: generatedPatternData.title,
        description: generatedPatternData.description || `A ${formData.skillLevel} level ${formData.projectType} crochet pattern.`,
        projectType: formData.projectType,
        skillLevel: formData.skillLevel,
        yarnType: formData.yarnType || undefined,
        size: formData.size || undefined,
        imgUrl: imageResponse.url, // Main image
        endProductImage: imageResponse.url, // Product image
        difficultyLevel: formData.skillLevel, // Map skill level to difficulty level
        completed: false, // New pattern starts as not completed
        materialsNotes: generatedPatternData.materialsNotes || "",
        yarnRequirements: generatedPatternData.yarnRequirements || [],
        hookRequirements: generatedPatternData.hookRequirements || [],
        notionsRequirements: generatedPatternData.notionsRequirements || [],
        toolRequirements: generatedPatternData.toolRequirements || [],
        sections: generatedPatternData.sections.map((section: any) => ({
          name: section.name,
          notes: section.notes || "",
          locked: false,
          partImageUrl: section.partImageUrl || null,
          steps: section.steps.map((step: any) => ({
            id: step.id,
            text: step.text,
            locked: false,
            count: 0,
            notes: '',
            photo: null,
            aiStepImage: null,
            completed: false
          }))
        }))
      };

      // Save the pattern
      const savedPattern = await savePatternMutation.mutateAsync(patternToSave);
      
      // Set the completion stage
      setGenerationStage('complete');
      
      // Give a short delay to show the completion animation
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      // Pass the saved pattern to the parent component
      onPatternCreated(savedPattern);
      
      toast({
        title: "Pattern Generated Successfully!",
        description: `Your "${savedPattern.title}" pattern is ready! You can now view the pattern details, instructions, and generate section images.`,
        duration: 6000,
      });
    } catch (error) {
      console.error('Error generating pattern:', error);
      
      // Provide more specific error messages based on error type
      let errorDescription = "There was an error generating your pattern. Please try again.";
      const errorString = String(error);
      
      // Check for API key related errors
      const isApiKeyError = errorString.includes('OPENAI_API_KEY') || 
                         errorString.includes('API key') || 
                         errorString.includes('authentication') || 
                         errorString.includes('Unauthorized') || 
                         errorString.includes('401') || 
                         errorString.includes('403') || 
                         errorString.includes('key invalid');
      
      if (isApiKeyError) {
        // Use the special API warning toast variant for API key issues
        toast({
          title: "OpenAI API Key Required",
          description: "To generate your crochet pattern, please add a valid OpenAI API key in your environment variables.",
          variant: "apiWarning",
          action: <ToastAction altText="Visit OpenAI" onClick={() => window.open('https://platform.openai.com/account/api-keys', '_blank')}>
                   <Key className="mr-1 h-4 w-4" />Get API Key
                </ToastAction>,
          duration: 10000, // Show for longer (10 seconds)
        });
      } 
      // Rate Limit Errors
      else if (errorString.includes('rate limit') || errorString.includes('429')) {
        toast({
          title: "Rate Limit Reached",
          description: "OpenAI API rate limit reached for pattern generation. Please try again in a few minutes when your quota resets.",
          variant: "apiWarning",
          duration: 8000,
        });
      } 
      // Timeout Errors
      else if (errorString.includes('timeout') || errorString.includes('timed out')) {
        toast({
          title: "Generation Timed Out",
          description: "The pattern generation request timed out. Try a simpler description or check your network connection.",
          variant: "apiWarning",
          duration: 8000,
        });
      }
      // Network Errors
      else if (errorString.includes('network') || errorString.includes('connection') || errorString.includes('ECONNRESET')) {
        toast({
          title: "Network Error",
          description: "Could not connect to the OpenAI API. Please check your internet connection and try again.",
          variant: "apiWarning",
          duration: 8000,
        });
      }
      // Billing Errors
      else if (errorString.includes('billing') || errorString.includes('payment') || errorString.includes('quota')) {
        toast({
          title: "OpenAI Billing Issue",
          description: "There's a billing issue with your OpenAI account. Please check your payment information or usage quota.",
          variant: "apiWarning",
          action: <ToastAction altText="Check Billing" onClick={() => window.open('https://platform.openai.com/account/billing', '_blank')}>
                    <ExternalLink className="mr-1 h-4 w-4" />Check Billing
                 </ToastAction>,
          duration: 10000,
        });
      }
      // Content Policy Violations
      else if (errorString.includes('content policy') || errorString.includes('safety') || errorString.includes('violation')) {
        toast({
          title: "Content Policy Violation",
          description: "Your pattern request may violate OpenAI's content policy. Please ensure your description doesn't contain inappropriate content.",
          variant: "apiWarning",
          action: <ToastAction altText="Learn More" onClick={() => window.open('https://openai.com/policies/usage-policies', '_blank')}>
                    <AlertCircle className="mr-1 h-4 w-4" />Learn More
                 </ToastAction>,
          duration: 10000,
        });
      } 
      // Generic Fallback Error
      else {
        toast({
          title: "Pattern Generation Failed",
          description: `Could not generate your crochet pattern. Error details: ${errorString.substring(0, 50)}${errorString.length > 50 ? '...' : ''}`,
          variant: "destructive",
          duration: 6000,
        });
      }
    } finally {
      setIsGenerating(false);
    }
  };

  const activeCategory = CATEGORIES.find(c => c.id === formData.projectType);

  const YALA_TIPS = [
    "Pick a category and I'll tailor the pattern just for you! 🐾",
    "More detail = a better pattern. Tell me everything! ✨",
    "Great colour choices make the magic happen 🎨",
    "A reference photo helps me imagine exactly what you want!",
    "I've got everything I need — let's create something beautiful! 🌟",
  ];

  return (
    <div className="flex flex-col gap-0 max-w-lg mx-auto w-full">

      {/* Progress bar */}
      <div className="flex items-center gap-1.5 mb-4">
        {WIZARD_STEPS.map((label, i) => (
          <div key={label} className="flex items-center gap-1.5 flex-1">
            <div className="flex flex-col items-center gap-1 flex-shrink-0">
              <div
                className="w-7 h-7 rounded-full flex items-center justify-center text-[11px] font-bold transition-all"
                style={{
                  background: i < wizardStep ? "#84934F" : i === wizardStep ? "#C24E6B" : "rgba(140,100,55,0.12)",
                  color: i <= wizardStep ? "white" : "#9A7868",
                  boxShadow: i === wizardStep ? "0 3px 10px rgba(194,78,107,0.35)" : "none",
                }}
              >{i < wizardStep ? "✓" : i + 1}</div>
              <span className="text-[9px] font-semibold whitespace-nowrap hidden sm:block"
                style={{ color: i === wizardStep ? "#C24E6B" : i < wizardStep ? "#84934F" : "#B0908A" }}>
                {label}
              </span>
            </div>
            {i < WIZARD_STEPS.length - 1 && (
              <div className="flex-1 h-[2px] rounded-full mt-[-12px] sm:mt-[-20px]"
                style={{ background: i < wizardStep ? "#84934F" : "rgba(140,100,55,0.15)" }} />
            )}
          </div>
        ))}
      </div>

      {/* Yala floating tip */}
      <div className="flex items-center gap-2.5 px-3 py-2.5 rounded-2xl mb-5"
        style={{ background: "rgba(124,95,168,0.07)", border: "1px dashed rgba(124,95,168,0.22)" }}>
        <img src="/characters/char-yala-transparent.png" alt="Yala"
          style={{ width: 36, height: 36, objectFit: "contain", flexShrink: 0 }}
          onError={(e) => { (e.target as HTMLImageElement).style.display = "none"; }} />
        <p className="text-[12px] italic leading-snug" style={{ color: "#7C5FA8" }}>
          "{YALA_TIPS[wizardStep]}"
        </p>
      </div>

      {/* ── Step 0: What are you making? ── */}
      {wizardStep === 0 && (
        <div>
          <div className="text-center mb-5">
            <h2 className="font-heading font-bold text-[22px]" style={{ color: "#3D2318" }}>What are you making?</h2>
            <p className="text-[13px] mt-1" style={{ color: "#9A7868" }}>Pick a category to get started</p>
          </div>
          <div className="grid grid-cols-1 gap-3">
            {CATEGORIES.map((cat) => (
              <button key={cat.id}
                onClick={() => setFormData(p => ({ ...p, projectType: cat.id }))}
                className="flex items-center gap-4 p-4 rounded-2xl transition-all hover:scale-[1.01] active:scale-[0.99]"
                style={{
                  background: formData.projectType === cat.id ? `${cat.color}14` : "rgba(255,252,245,0.9)",
                  border: `2px solid ${formData.projectType === cat.id ? cat.color : "rgba(140,100,55,0.18)"}`,
                  boxShadow: formData.projectType === cat.id ? `0 4px 20px ${cat.color}25` : "0 1px 4px rgba(60,30,10,0.06)",
                }}>
                <span style={{ fontSize: 32 }}>{cat.emoji}</span>
                <div className="text-left flex-1">
                  <p className="font-heading font-bold text-[15px]" style={{ color: "#3D2318" }}>{cat.label}</p>
                </div>
                {formData.projectType === cat.id && (
                  <div className="w-6 h-6 rounded-full flex items-center justify-center flex-shrink-0"
                    style={{ background: cat.color }}>
                    <span className="text-white text-[11px] font-bold">✓</span>
                  </div>
                )}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* ── Step 1: Details ── */}
      {wizardStep === 1 && (
        <div className="flex flex-col gap-4">
          <div className="text-center mb-1">
            <h2 className="font-heading font-bold text-[22px]" style={{ color: "#3D2318" }}>Tell us about it</h2>
            <p className="text-[13px] mt-1" style={{ color: "#9A7868" }}>Describe your vision and skill level</p>
          </div>

          {/* Prompt */}
          <div>
            <label className="block font-heading font-semibold text-[13px] mb-2" style={{ color: "#5C3A28" }}>
              Describe your idea ✨
            </label>
            <textarea
              rows={4}
              placeholder="e.g. A cosy sunflower bag for everyday use, in pastel yellow and green…"
              value={formData.prompt}
              onChange={handlePromptChange}
              className="w-full p-4 rounded-2xl text-[13px] leading-relaxed outline-none resize-none transition-all"
              style={{
                background: "rgba(255,252,245,0.95)",
                border: "1.5px solid rgba(140,100,55,0.22)",
                color: "#3D2318",
              }}
            />
          </div>

          {/* Skill level */}
          <div>
            <label className="block font-heading font-semibold text-[13px] mb-2" style={{ color: "#5C3A28" }}>Skill Level</label>
            <div className="flex gap-2">
              {SKILL_LEVELS.map((lvl) => (
                <button key={lvl.id}
                  onClick={() => setFormData(p => ({ ...p, skillLevel: lvl.id }))}
                  className="flex-1 flex flex-col items-center gap-1 p-3 rounded-2xl transition-all"
                  style={{
                    background: formData.skillLevel === lvl.id ? "rgba(194,78,107,0.10)" : "rgba(255,252,245,0.9)",
                    border: `1.5px solid ${formData.skillLevel === lvl.id ? "#C24E6B" : "rgba(140,100,55,0.18)"}`,
                  }}>
                  <span style={{ fontSize: 22 }}>{lvl.emoji}</span>
                  <span className="text-[11px] font-bold" style={{ color: formData.skillLevel === lvl.id ? "#C24E6B" : "#5C3A28" }}>
                    {lvl.id}
                  </span>
                  <span className="text-[9.5px] text-center" style={{ color: "#9A7868" }}>{lvl.desc}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Size */}
          <div>
            <label className="block font-heading font-semibold text-[13px] mb-2" style={{ color: "#5C3A28" }}>
              Approximate Size
            </label>
            <div className="flex flex-wrap gap-2">
              {SIZE_OPTIONS.map((sz) => (
                <button key={sz}
                  onClick={() => setFormData(p => ({ ...p, size: sz }))}
                  className="px-3.5 py-2 rounded-xl text-[12px] font-semibold transition-all"
                  style={{
                    background: formData.size === sz ? "rgba(132,147,79,0.14)" : "rgba(255,252,245,0.9)",
                    border: `1.5px solid ${formData.size === sz ? "#84934F" : "rgba(140,100,55,0.18)"}`,
                    color: formData.size === sz ? "#84934F" : "#5C3A28",
                  }}>
                  {sz}
                </button>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* ── Step 2: Yarn & Colours ── */}
      {wizardStep === 2 && (
        <div className="flex flex-col gap-4">
          <div className="text-center mb-1">
            <h2 className="font-heading font-bold text-[22px]" style={{ color: "#3D2318" }}>Yarn & Colours</h2>
            <p className="text-[13px] mt-1" style={{ color: "#9A7868" }}>Choose your materials (optional)</p>
          </div>

          <div>
            <label className="block font-heading font-semibold text-[13px] mb-2" style={{ color: "#5C3A28" }}>Yarn Type</label>
            <div className="flex flex-wrap gap-2">
              {YARN_TYPES.map((yt) => (
                <button key={yt}
                  onClick={() => setFormData(p => ({ ...p, yarnType: yt === "Let AI decide" ? "" : yt }))}
                  className="px-3.5 py-2 rounded-xl text-[12px] font-semibold transition-all"
                  style={{
                    background: (formData.yarnType === yt || (yt === "Let AI decide" && !formData.yarnType)) ? "rgba(212,146,26,0.14)" : "rgba(255,252,245,0.9)",
                    border: `1.5px solid ${(formData.yarnType === yt || (yt === "Let AI decide" && !formData.yarnType)) ? "#D4921A" : "rgba(140,100,55,0.18)"}`,
                    color: (formData.yarnType === yt || (yt === "Let AI decide" && !formData.yarnType)) ? "#D4921A" : "#5C3A28",
                  }}>
                  {yt}
                </button>
              ))}
            </div>
          </div>

          <div>
            <label className="block font-heading font-semibold text-[13px] mb-2" style={{ color: "#5C3A28" }}>
              Colour Palette
              {wizardColors.length > 0 && <span className="ml-2 text-[11px] font-normal" style={{ color: "#9A7868" }}>({wizardColors.length} selected)</span>}
            </label>
            <div className="flex flex-wrap gap-2.5">
              {COLOR_PALETTE.map((c) => (
                <button key={c}
                  onClick={() => setWizardColors(prev => prev.includes(c) ? prev.filter(x => x !== c) : [...prev, c])}
                  className="w-9 h-9 rounded-xl transition-all hover:scale-110 active:scale-95"
                  style={{
                    background: c,
                    border: wizardColors.includes(c) ? "3px solid #3D2318" : "2px solid rgba(255,255,255,0.6)",
                    boxShadow: wizardColors.includes(c) ? "0 0 0 2px rgba(255,255,255,0.8), 0 2px 8px rgba(0,0,0,0.2)" : "0 1px 4px rgba(0,0,0,0.12)",
                  }}
                />
              ))}
            </div>
          </div>
        </div>
      )}

      {/* ── Step 3: Inspiration ── */}
      {wizardStep === 3 && (
        <div className="flex flex-col gap-4">
          <div className="text-center mb-1">
            <h2 className="font-heading font-bold text-[22px]" style={{ color: "#3D2318" }}>Inspiration Photo</h2>
            <p className="text-[13px] mt-1" style={{ color: "#9A7868" }}>Upload a reference image (optional)</p>
          </div>

          <div
            onClick={() => document.getElementById("wizard-file-input")?.click()}
            className="border-2 border-dashed rounded-2xl flex flex-col items-center justify-center gap-3 cursor-pointer transition-all"
            style={{
              borderColor: file ? "#84934F" : "rgba(140,100,55,0.35)",
              background: file ? "rgba(132,147,79,0.06)" : "rgba(255,252,245,0.7)",
              minHeight: 200,
            }}>
            <input id="wizard-file-input" type="file" accept="image/*" className="hidden" onChange={handleFileChange} />
            {file ? (
              <div className="text-center px-4">
                <span style={{ fontSize: 40 }}>🖼️</span>
                <p className="font-semibold text-[14px] mt-2" style={{ color: "#84934F" }}>{file.name}</p>
                <button onClick={(e) => { e.stopPropagation(); setFile(null); }}
                  className="text-[11px] mt-1 underline" style={{ color: "#9A7868" }}>Remove</button>
              </div>
            ) : (
              <>
                <span style={{ fontSize: 44 }}>📸</span>
                <div className="text-center">
                  <p className="font-heading font-semibold text-[14px]" style={{ color: "#5C3A28" }}>Drop a photo here</p>
                  <p className="text-[12px] mt-0.5" style={{ color: "#9A7868" }}>or tap to browse</p>
                </div>
              </>
            )}
          </div>

          <button onClick={() => setWizardStep(4)}
            className="w-full py-2.5 rounded-xl text-[13px] font-semibold transition-all"
            style={{ background: "rgba(140,100,55,0.08)", color: "#9A7868", border: "1px dashed rgba(140,100,55,0.25)" }}>
            Skip this step →
          </button>
        </div>
      )}

      {/* ── Step 4: Review & Generate ── */}
      {wizardStep === 4 && (
        <div className="flex flex-col gap-4">
          <div className="text-center mb-1">
            <h2 className="font-heading font-bold text-[22px]" style={{ color: "#3D2318" }}>Ready to create!</h2>
            <p className="text-[13px] mt-1" style={{ color: "#9A7868" }}>Yala will craft your pattern ✨</p>
          </div>

          {/* Summary card */}
          <div className="craft-card p-4 flex flex-col gap-2.5">
            <div className="flex items-center gap-3 pb-2.5" style={{ borderBottom: "1px dashed rgba(140,100,55,0.2)" }}>
              <span style={{ fontSize: 28 }}>{activeCategory?.emoji ?? "🧶"}</span>
              <div>
                <p className="font-heading font-bold text-[15px]" style={{ color: "#3D2318" }}>{formData.projectType || "—"}</p>
                <p className="text-[11px]" style={{ color: "#9A7868" }}>{formData.skillLevel}</p>
              </div>
            </div>
            {formData.prompt && (
              <div>
                <p className="text-[10.5px] font-semibold uppercase tracking-wider mb-1" style={{ color: "#B0908A" }}>Description</p>
                <p className="text-[12.5px] leading-snug" style={{ color: "#5C3A28" }}>{formData.prompt}</p>
              </div>
            )}
            <div className="flex flex-wrap gap-2 pt-1">
              {formData.size && <span className="badge-green">{formData.size}</span>}
              {formData.yarnType && <span className="px-2.5 py-0.5 rounded-full text-[11px] font-semibold" style={{ background: "rgba(212,146,26,0.12)", color: "#D4921A" }}>{formData.yarnType}</span>}
              {wizardColors.length > 0 && (
                <div className="flex items-center gap-1.5">
                  {wizardColors.slice(0, 5).map(c => (
                    <div key={c} className="w-4 h-4 rounded-full border-2 border-white" style={{ background: c, boxShadow: "0 1px 3px rgba(0,0,0,0.15)" }} />
                  ))}
                  {wizardColors.length > 5 && <span className="text-[10px]" style={{ color: "#9A7868" }}>+{wizardColors.length - 5}</span>}
                </div>
              )}
              {file && <span className="text-[11px]" style={{ color: "#84934F" }}>📸 Reference image</span>}
            </div>
          </div>

          {/* Yala */}
          <div className="flex items-center gap-3 px-3 py-3 rounded-2xl" style={{ background: "rgba(124,95,168,0.08)", border: "1px dashed rgba(124,95,168,0.25)" }}>
            <img src="/characters/char-yala-transparent.png" alt="Yala"
              style={{ width: 48, height: 48, objectFit: "contain" }}
              onError={(e) => { (e.target as HTMLImageElement).style.display = "none"; }} />
            <p className="text-[12px] italic leading-snug" style={{ color: "#7C5FA8" }}>
              "I've got everything I need. Let me weave some magic for you!"
            </p>
          </div>

          {/* Generate button */}
          <button
            onClick={handleGeneratePattern}
            disabled={isGenerating}
            className="w-full py-4 rounded-2xl font-heading font-bold text-[16px] flex items-center justify-center gap-2 transition-all hover:opacity-90 active:scale-[0.98]"
            style={{
              background: isGenerating ? "rgba(194,78,107,0.4)" : "linear-gradient(135deg, #C24E6B, #A83050)",
              color: "white",
              boxShadow: isGenerating ? "none" : "0 6px 24px rgba(194,78,107,0.4)",
            }}>
            {isGenerating ? (
              <><span className="animate-spin">🧶</span> Generating…</>
            ) : (
              <><Sparkles className="h-5 w-5" /> Generate with Yala</>
            )}
          </button>
        </div>
      )}

      {/* Navigation */}
      <div className="flex items-center justify-between mt-6">
        <button
          onClick={() => setWizardStep(s => Math.max(0, s - 1))}
          disabled={wizardStep === 0}
          className="px-5 py-2.5 rounded-xl text-[13px] font-semibold transition-all hover:opacity-80 disabled:opacity-30"
          style={{ background: "rgba(140,100,55,0.09)", color: "#5C3A28" }}>
          ← Back
        </button>
        {wizardStep < 4 && (
          <button
            onClick={() => canAdvance() && setWizardStep(s => s + 1)}
            disabled={!canAdvance()}
            className="px-6 py-2.5 rounded-xl font-heading font-bold text-[13px] transition-all hover:opacity-90 disabled:opacity-35"
            style={{
              background: canAdvance() ? "linear-gradient(135deg, #C24E6B, #A83050)" : "rgba(140,100,55,0.12)",
              color: canAdvance() ? "white" : "#9A7868",
              boxShadow: canAdvance() ? "0 3px 12px rgba(194,78,107,0.35)" : "none",
            }}>
            {wizardStep === 3 ? "Review →" : "Next →"}
          </button>
        )}
      </div>
    </div>
  );
};

export default PatternInputRefactored;